//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Grabber_Web.ServiceProduct {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cost_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double gainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cost_price {
            get {
                return this.cost_priceField;
            }
            set {
                if ((this.cost_priceField.Equals(value) != true)) {
                    this.cost_priceField = value;
                    this.RaisePropertyChanged("cost_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double gain {
            get {
                return this.gainField;
            }
            set {
                if ((this.gainField.Equals(value) != true)) {
                    this.gainField = value;
                    this.RaisePropertyChanged("gain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.product_codeField, value) != true)) {
                    this.product_codeField = value;
                    this.RaisePropertyChanged("product_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProduct.IProductControl")]
    public interface IProductControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Delete", ReplyAction="http://tempuri.org/IControlableOf_Product/DeleteResponse")]
        void Delete(Order_Grabber_Web.ServiceProduct.Product element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Delete", ReplyAction="http://tempuri.org/IControlableOf_Product/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceProduct.Product element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Edit", ReplyAction="http://tempuri.org/IControlableOf_Product/EditResponse")]
        void Edit(Order_Grabber_Web.ServiceProduct.Product element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Edit", ReplyAction="http://tempuri.org/IControlableOf_Product/EditResponse")]
        System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceProduct.Product element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Create", ReplyAction="http://tempuri.org/IControlableOf_Product/CreateResponse")]
        void Create(Order_Grabber_Web.ServiceProduct.Product new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/Create", ReplyAction="http://tempuri.org/IControlableOf_Product/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceProduct.Product new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Product/GetByResponse")]
        Order_Grabber_Web.ServiceProduct.Product GetBy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Product/GetByResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceProduct.Product> GetByAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Product/GetAllResponse")]
        Order_Grabber_Web.ServiceProduct.Product[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Product/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Product/GetAllResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceProduct.Product[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductControlChannel : Order_Grabber_Web.ServiceProduct.IProductControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductControlClient : System.ServiceModel.ClientBase<Order_Grabber_Web.ServiceProduct.IProductControl>, Order_Grabber_Web.ServiceProduct.IProductControl {
        
        public ProductControlClient() {
        }
        
        public ProductControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Delete(Order_Grabber_Web.ServiceProduct.Product element) {
            base.Channel.Delete(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceProduct.Product element) {
            return base.Channel.DeleteAsync(element);
        }
        
        public void Edit(Order_Grabber_Web.ServiceProduct.Product element) {
            base.Channel.Edit(element);
        }
        
        public System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceProduct.Product element) {
            return base.Channel.EditAsync(element);
        }
        
        public void Create(Order_Grabber_Web.ServiceProduct.Product new_element) {
            base.Channel.Create(new_element);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceProduct.Product new_element) {
            return base.Channel.CreateAsync(new_element);
        }
        
        public Order_Grabber_Web.ServiceProduct.Product GetBy(int id) {
            return base.Channel.GetBy(id);
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceProduct.Product> GetByAsync(int id) {
            return base.Channel.GetByAsync(id);
        }
        
        public Order_Grabber_Web.ServiceProduct.Product[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceProduct.Product[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
