//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Grabber_Web.ServiceCustomer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string document_nroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string document_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Order_Grabber_Web.ServiceCustomer.Order[] ordersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((this.client_idField.Equals(value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_name {
            get {
                return this.customer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_nameField, value) != true)) {
                    this.customer_nameField = value;
                    this.RaisePropertyChanged("customer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string document_nro {
            get {
                return this.document_nroField;
            }
            set {
                if ((object.ReferenceEquals(this.document_nroField, value) != true)) {
                    this.document_nroField = value;
                    this.RaisePropertyChanged("document_nro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string document_type {
            get {
                return this.document_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.document_typeField, value) != true)) {
                    this.document_typeField = value;
                    this.RaisePropertyChanged("document_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Order_Grabber_Web.ServiceCustomer.Order[] orders {
            get {
                return this.ordersField;
            }
            set {
                if ((object.ReferenceEquals(this.ordersField, value) != true)) {
                    this.ordersField = value;
                    this.RaisePropertyChanged("orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Order_Grabber_Web.ServiceCustomer.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int client_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime order_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Order_Grabber_Web.ServiceCustomer.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int client_id {
            get {
                return this.client_idField;
            }
            set {
                if ((this.client_idField.Equals(value) != true)) {
                    this.client_idField = value;
                    this.RaisePropertyChanged("client_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime order_date {
            get {
                return this.order_dateField;
            }
            set {
                if ((this.order_dateField.Equals(value) != true)) {
                    this.order_dateField = value;
                    this.RaisePropertyChanged("order_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((this.order_idField.Equals(value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCustomer.ICustomerControl")]
    public interface ICustomerControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Delete", ReplyAction="http://tempuri.org/IControlableOf_Customer/DeleteResponse")]
        void Delete(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Delete", ReplyAction="http://tempuri.org/IControlableOf_Customer/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Edit", ReplyAction="http://tempuri.org/IControlableOf_Customer/EditResponse")]
        void Edit(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Edit", ReplyAction="http://tempuri.org/IControlableOf_Customer/EditResponse")]
        System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Create", ReplyAction="http://tempuri.org/IControlableOf_Customer/CreateResponse")]
        void Create(Order_Grabber_Web.ServiceCustomer.Customer new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Create", ReplyAction="http://tempuri.org/IControlableOf_Customer/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceCustomer.Customer new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetByResponse")]
        Order_Grabber_Web.ServiceCustomer.Customer GetBy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetByResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer> GetByAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetAllResponse")]
        Order_Grabber_Web.ServiceCustomer.Customer[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetAllResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerControl/GetAllOrders", ReplyAction="http://tempuri.org/ICustomerControl/GetAllOrdersResponse")]
        Order_Grabber_Web.ServiceCustomer.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerControl/GetAllOrders", ReplyAction="http://tempuri.org/ICustomerControl/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Order[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerControl/GetOrderBy", ReplyAction="http://tempuri.org/ICustomerControl/GetOrderByResponse")]
        Order_Grabber_Web.ServiceCustomer.Order GetOrderBy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerControl/GetOrderBy", ReplyAction="http://tempuri.org/ICustomerControl/GetOrderByResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Order> GetOrderByAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerControlChannel : Order_Grabber_Web.ServiceCustomer.ICustomerControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerControlClient : System.ServiceModel.ClientBase<Order_Grabber_Web.ServiceCustomer.ICustomerControl>, Order_Grabber_Web.ServiceCustomer.ICustomerControl {
        
        public CustomerControlClient() {
        }
        
        public CustomerControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Delete(Order_Grabber_Web.ServiceCustomer.Customer element) {
            base.Channel.Delete(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceCustomer.Customer element) {
            return base.Channel.DeleteAsync(element);
        }
        
        public void Edit(Order_Grabber_Web.ServiceCustomer.Customer element) {
            base.Channel.Edit(element);
        }
        
        public System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceCustomer.Customer element) {
            return base.Channel.EditAsync(element);
        }
        
        public void Create(Order_Grabber_Web.ServiceCustomer.Customer new_element) {
            base.Channel.Create(new_element);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceCustomer.Customer new_element) {
            return base.Channel.CreateAsync(new_element);
        }
        
        public Order_Grabber_Web.ServiceCustomer.Customer GetBy(int id) {
            return base.Channel.GetBy(id);
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer> GetByAsync(int id) {
            return base.Channel.GetByAsync(id);
        }
        
        public Order_Grabber_Web.ServiceCustomer.Customer[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Order_Grabber_Web.ServiceCustomer.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Order[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public Order_Grabber_Web.ServiceCustomer.Order GetOrderBy(int id) {
            return base.Channel.GetOrderBy(id);
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Order> GetOrderByAsync(int id) {
            return base.Channel.GetOrderByAsync(id);
        }
    }
}
