//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Grabber_Web.ServiceCustomer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Customer_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Document_nroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Order_Grabber_Web.ServiceCustomer.TipoDocumento> Document_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Order_Grabber_Web.ServiceCustomer.Estado> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Order_Grabber_Web.ServiceCustomer.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_name {
            get {
                return this.Customer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Customer_nameField, value) != true)) {
                    this.Customer_nameField = value;
                    this.RaisePropertyChanged("Customer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document_nro {
            get {
                return this.Document_nroField;
            }
            set {
                if ((object.ReferenceEquals(this.Document_nroField, value) != true)) {
                    this.Document_nroField = value;
                    this.RaisePropertyChanged("Document_nro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Order_Grabber_Web.ServiceCustomer.TipoDocumento> Document_type {
            get {
                return this.Document_typeField;
            }
            set {
                if ((this.Document_typeField.Equals(value) != true)) {
                    this.Document_typeField = value;
                    this.RaisePropertyChanged("Document_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Order_Grabber_Web.ServiceCustomer.Estado> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Order_Grabber_Web.ServiceCustomer.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    public enum TipoDocumento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DNI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIBRETA_ENROLAMIENTO = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INACTIVO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDIENTE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIN_STOCK = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Order_Grabber_DataService.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Order_Grabber_Web.ServiceCustomer.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Order_Grabber_Web.ServiceCustomer.Estado EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Order_Grabber_Web.ServiceCustomer.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Order_Grabber_Web.ServiceCustomer.Estado Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Order_date {
            get {
                return this.Order_dateField;
            }
            set {
                if ((this.Order_dateField.Equals(value) != true)) {
                    this.Order_dateField = value;
                    this.RaisePropertyChanged("Order_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCustomer.ICustomerControl")]
    public interface ICustomerControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Delete", ReplyAction="http://tempuri.org/IControlableOf_Customer/DeleteResponse")]
        void Delete(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Delete", ReplyAction="http://tempuri.org/IControlableOf_Customer/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Edit", ReplyAction="http://tempuri.org/IControlableOf_Customer/EditResponse")]
        void Edit(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Edit", ReplyAction="http://tempuri.org/IControlableOf_Customer/EditResponse")]
        System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceCustomer.Customer element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Create", ReplyAction="http://tempuri.org/IControlableOf_Customer/CreateResponse")]
        void Create(Order_Grabber_Web.ServiceCustomer.Customer new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/Create", ReplyAction="http://tempuri.org/IControlableOf_Customer/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceCustomer.Customer new_element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetByResponse")]
        Order_Grabber_Web.ServiceCustomer.Customer GetBy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetBy", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetByResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer> GetByAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetAllResponse")]
        Order_Grabber_Web.ServiceCustomer.Customer[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlableOf_Customer/GetAll", ReplyAction="http://tempuri.org/IControlableOf_Customer/GetAllResponse")]
        System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerControlChannel : Order_Grabber_Web.ServiceCustomer.ICustomerControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerControlClient : System.ServiceModel.ClientBase<Order_Grabber_Web.ServiceCustomer.ICustomerControl>, Order_Grabber_Web.ServiceCustomer.ICustomerControl {
        
        public CustomerControlClient() {
        }
        
        public CustomerControlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerControlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Delete(Order_Grabber_Web.ServiceCustomer.Customer element) {
            base.Channel.Delete(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Order_Grabber_Web.ServiceCustomer.Customer element) {
            return base.Channel.DeleteAsync(element);
        }
        
        public void Edit(Order_Grabber_Web.ServiceCustomer.Customer element) {
            base.Channel.Edit(element);
        }
        
        public System.Threading.Tasks.Task EditAsync(Order_Grabber_Web.ServiceCustomer.Customer element) {
            return base.Channel.EditAsync(element);
        }
        
        public void Create(Order_Grabber_Web.ServiceCustomer.Customer new_element) {
            base.Channel.Create(new_element);
        }
        
        public System.Threading.Tasks.Task CreateAsync(Order_Grabber_Web.ServiceCustomer.Customer new_element) {
            return base.Channel.CreateAsync(new_element);
        }
        
        public Order_Grabber_Web.ServiceCustomer.Customer GetBy(int id) {
            return base.Channel.GetBy(id);
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer> GetByAsync(int id) {
            return base.Channel.GetByAsync(id);
        }
        
        public Order_Grabber_Web.ServiceCustomer.Customer[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Order_Grabber_Web.ServiceCustomer.Customer[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }

        internal object GetAllOrders()
        {
            throw new NotImplementedException();
        }
    }
}
